kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: ubuntu-rsync
  namespace: ocellus-cwk
  labels:
    app: ubuntu-rsync
spec:
  volumes:
    -
      name: volume-5l0wr
      persistentVolumeClaim:
        claimName: ocellus-cwk-claim1
  template: 
    metadata:
      labels:
        name: ubuntu-rsync
    spec:
      containers:
        - name: ubuntu-rsync
          image: 172.30.237.129:5000/ocellus-cwk/ubuntu-rsync
          ports:
            - containerPort: 80
              protocol: "TCP"
            - containerPort: 443
              protocol: "TCP"
          volumeMounts:
            -
              name: ocellus-cwk-claim1
              mountPath: /usr/share/ocellus
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
  replicas: 1 
  selector:
    app: ubuntu-rsync
    deploymentconfig: ubuntu-rsync
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - ubuntu-rsync
        from:
          kind: "ImageStreamTag"
          name: "ubuntu-rsync:latest"
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {  }